### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by dendi239** [romasku/money-log-docs#1]
We can use as well [ISO 18245 codes](https://docs.checkout.com/resources/codes/merchant-category-codes) to identify transaction types. Therefore, I'd like to suggest using at optional user-defined name and ISO-code, which may be convenient for different integrations — for example, [monobank API provides ISO-code for each transaction](https://api.monobank.ua/docs/). There's room for improvement: for example, we may use them to create user-defined groups like restraunts+supermarkets.

**Comment by romasku** [comment]
I think it is better to import _iso-codes_ as _custom field_ and allow the user to specify a way to deduce _category_ for _iso code_. My reasoning:

- These codes are poor for manually entered spending. The list is large, some entries contain some too detailed stuff (like the hotel network name). So making it required will be bad for use cases when a user adds a lot of spending by hand.
- Codes are not always represented the human understood "category" of spending. I can buy an electric lamp in the supermarket and get the "Food" category.
- Users can define some custom category (like "presents") that has no corresponding to any ISO code.

Though I agree that ISO codes will be the only source of info for imported spending, and we will have to use them. I suggest the following: when the users import a new bunch of spending, we group them by iso code, select one representative for each group and ask users to select the category manually. We also save decision about given ISO code and do not ask on subsequent imports. Also, there should be an "import review" screen where users see all newly imported spendings and can adjust categories for some of them. And we should store ISO code as a custom field, so that if users really want to get stats for ISO codes - they can use a special query for that.

What do you think?

**Comment by dendi239** [comment]
Yeah, I can agree that using these ISO codes makes sense during the import process only and will be a great source of information to guess category, but user still should have ability to setup it by himself.
